language: python
python:
  - "3.3"
  - "2.7"
install:
  - "pip install -r requirements.txt"
script:
 - "python -m unittest discover"
 - "python hpo_similarity.py \
   --genes data/example_genes.json \
   --phenotypes data/example_phenotypes.json"
