language: python
python:
  - "3.3"
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - pip install coveralls
script:
 - "python -m unittest discover"
 - "python hpo_similarity.py \
   --genes data/example_genes.json \
   --phenotypes data/example_phenotypes.json"
 - python -m coverage run --source=./ -m unittest discover
after_success:
 - coveralls
