language: python
python:
  - 3.3
  - 2.7
install:
  - python setup.py install
  - pip install coveralls
script:
 - python -m unittest discover
 - python scripts/proband_similarity.py \
   --genes data/example_genes.json \
   --phenotypes data/example_phenotypes.json
 - python -m coverage run --source=./ -m unittest discover
after_success:
 - coveralls
