language: python
python:
  - 3.4
  - 2.7
install:
  - python setup.py install
  - pip install coveralls
script:
 - python setup.py test
 - "python scripts/proband_similarity.py \
   --genes data/example_genes.json \
   --phenotypes data/example_phenotypes.json"
 - python -m coverage run --source=./ -m unittest discover
after_success:
 - coveralls
