language: python
python:
  - 3.5
  - 3.7
install:
  - python setup.py install
  - pip install coveralls
script:
 - python setup.py test
 - "hpo_similarity \
   --genes data/example_genes.json \
   --phenotypes data/example_phenotypes.json"
 - python -m coverage run --source=./ -m unittest discover
after_success:
 - coveralls
